/* Generated By:JavaCC: Do not edit this line. FormulaParserConstants.java */
package org.openlca.expressions;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FormulaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int MULTIPLY = 10;
  /** RegularExpression Id. */
  int DIVIDE = 11;
  /** RegularExpression Id. */
  int INTDIVIDE = 12;
  /** RegularExpression Id. */
  int LT = 13;
  /** RegularExpression Id. */
  int LTEQ = 14;
  /** RegularExpression Id. */
  int EQ = 15;
  /** RegularExpression Id. */
  int NEQ = 16;
  /** RegularExpression Id. */
  int GT = 17;
  /** RegularExpression Id. */
  int GTEQ = 18;
  /** RegularExpression Id. */
  int POW = 19;
  /** RegularExpression Id. */
  int MOD = 20;
  /** RegularExpression Id. */
  int XOR = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int DIGITS = 23;
  /** RegularExpression Id. */
  int EXPONENT = 24;
  /** RegularExpression Id. */
  int NUMBER = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int OTHERCHARS = 27;
  /** RegularExpression Id. */
  int IDENTIFIER = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "<AND>",
    "<OR>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"div\"",
    "\"<\"",
    "\"<=\"",
    "<EQ>",
    "<NEQ>",
    "\">\"",
    "\">=\"",
    "\"^\"",
    "\"mod\"",
    "\"xor\"",
    "<DIGIT>",
    "<DIGITS>",
    "<EXPONENT>",
    "<NUMBER>",
    "<LETTER>",
    "<OTHERCHARS>",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\";\"",
  };

}
