-- connect to the database
CONNECT 'jdbc:derby:C:/Users/Besitzer/openLCA-data-1.4/databases/ecoinvent_3_2_apos';
	
-- export tables
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'SEQUENCE', 'exp/SEQUENCE.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'OPENLCA_VERSION', 'exp/OPENLCA_VERSION.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_CATEGORIES', 'exp/TBL_CATEGORIES.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_ACTORS', 'exp/TBL_ACTORS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_LOCATIONS', 'exp/TBL_LOCATIONS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_SOURCES', 'exp/TBL_SOURCES.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_UNITS', 'exp/TBL_UNITS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_UNIT_GROUPS', 'exp/TBL_UNIT_GROUPS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_FLOW_PROPERTIES', 'exp/TBL_FLOW_PROPERTIES.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_FLOWS', 'exp/TBL_FLOWS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_FLOW_PROPERTY_FACTORS', 'exp/TBL_FLOW_PROPERTY_FACTORS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_PROCESSES', 'exp/TBL_PROCESSES.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_PROCESS_DOCS', 'exp/TBL_PROCESS_DOCS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_PROCESS_SOURCES', 'exp/TBL_PROCESS_SOURCES.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_EXCHANGES', 'exp/TBL_EXCHANGES.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_ALLOCATION_FACTORS', 'exp/TBL_ALLOCATION_FACTORS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_PRODUCT_SYSTEMS', 'exp/TBL_PRODUCT_SYSTEMS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_PRODUCT_SYSTEM_PROCESSES', 'exp/TBL_PRODUCT_SYSTEM_PROCESSES.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_PROCESS_LINKS', 'exp/TBL_PROCESS_LINKS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_IMPACT_METHODS', 'exp/TBL_IMPACT_METHODS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_IMPACT_CATEGORIES', 'exp/TBL_IMPACT_CATEGORIES.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_IMPACT_FACTORS', 'exp/TBL_IMPACT_FACTORS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_NW_SETS', 'exp/TBL_NW_SETS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_NW_FACTORS', 'exp/TBL_NW_FACTORS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_PARAMETERS', 'exp/TBL_PARAMETERS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_PARAMETER_REDEFS', 'exp/TBL_PARAMETER_REDEFS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_PROJECTS', 'exp/TBL_PROJECTS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_PROJECT_VARIANTS', 'exp/TBL_PROJECT_VARIANTS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_CURRENCIES', 'exp/TBL_CURRENCIES.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_SOCIAL_INDICATORS', 'exp/TBL_SOCIAL_INDICATORS.csv',  
    ',', '"',  'UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE ('APP',  'TBL_SOCIAL_ASPECTS', 'exp/TBL_SOCIAL_ASPECTS.csv',  
    ',', '"',  'UTF-8');
