package org.openlca.simapro.csv;

import static org.junit.Assert.assertEquals;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.text.SimpleDateFormat;

import org.junit.Before;
import org.junit.Test;
import org.openlca.simapro.csv.io.BlockReader;
import org.openlca.simapro.csv.io.ModelReader;
import org.openlca.simapro.csv.model.enums.BoundaryWithNature;
import org.openlca.simapro.csv.model.enums.CutOffRule;
import org.openlca.simapro.csv.model.enums.Geography;
import org.openlca.simapro.csv.model.enums.ProcessAllocation;
import org.openlca.simapro.csv.model.enums.ProcessCategory;
import org.openlca.simapro.csv.model.enums.ProcessType;
import org.openlca.simapro.csv.model.enums.ProductType;
import org.openlca.simapro.csv.model.enums.Representativeness;
import org.openlca.simapro.csv.model.enums.Status;
import org.openlca.simapro.csv.model.enums.Substitution;
import org.openlca.simapro.csv.model.enums.Technology;
import org.openlca.simapro.csv.model.enums.TimePeriod;
import org.openlca.simapro.csv.model.process.ProcessBlock;

public class ProcessBlockTest {

	private ProcessBlock block;

	@Before
	public void setUp() throws Exception {
		try (InputStream is = this.getClass().getResourceAsStream(
				"simple_process.csv");
				InputStreamReader reader = new InputStreamReader(is);
				BlockReader blockReader = new BlockReader(reader);
				ModelReader modelReader = new ModelReader(blockReader,
						CsvConfig.getDefault(), ProcessBlock.class)) {
			this.block = (ProcessBlock) modelReader.read();
		}
	}

	@Test
	public void testTextEntries() {
		assertEquals("DefaultX25250700002", block.identifier);
		assertEquals("Test process", block.name);
		assertEquals("First order (only primary flows)",
				block.capitalGoods);
		assertEquals("data entry by: [System]", block.record);
		assertEquals("generated by: [System]", block.generator);
		assertEquals("text for collection method", block.collectionMethod);
		assertEquals("text for data treatment", block.dataTreatment);
		assertEquals("text for verification", block.verification);
		assertEquals("text for comment", block.comment);
		assertEquals("text for allocation rules", block.allocationRules);
	}

	@Test
	public void testEnumEntries() {
		assertEquals(ProcessCategory.MATERIAL, block.category);
		assertEquals(ProcessType.UNIT_PROCESS, block.processType);
		assertEquals(Status.DRAFT, block.status);
		assertEquals(TimePeriod.P_2005_2009, block.time);
		assertEquals(Geography.MIXED_DATA, block.geography);
		assertEquals(Technology.WORST_CASE, block.technology);
		assertEquals(Representativeness.THEORETICAL_CALCULATION,
				block.representativeness);
		assertEquals(ProcessAllocation.PHYSICAL_CAUSALITY,
				block.allocation);
		assertEquals(Substitution.ACTUAL_SUBSTITUTION, block.substitution);
		assertEquals(CutOffRule.PHYSICAL_LESS_THAN_1, block.cutoff);
		assertEquals(BoundaryWithNature.AGRICULTURAL_PRODUCTION_SYSTEM,
				block.boundaryWithNature);
	}

	@Test
	public void testElementaryExchanges() {
		assertEquals("Acids", block.resources.get(0).name);
		assertEquals("(+-)-Citronellol", block.emissionsToAir.get(0).name);
		assertEquals("(1r,4r)-(+)-Camphor", block.emissionsToWater.get(0).name);
		assertEquals("1'-Acetoxysafrole", block.emissionsToSoil.get(0).name);
		assertEquals("Asbestos", block.finalWasteFlows.get(0).name);
		assertEquals("Noise from bus km", block.nonMaterialEmissions
		.get(0).name);
		assertEquals("venting of argon, crude, liquid", block.socialIssues
		.get(0).name);
		assertEquals("Sample economic issue", block.economicIssues.get(0).name);
	}

	@Test
	public void testProductRow() {
		assertEquals(1, block.products.size());
		assertEquals("my product", block.products.get(0).name);
	}

	@Test
	public void testProductExchanges() {
		for (ProductType productType : ProductType.values())
			assertEquals(1, block.getProductExchanges(productType).size());
		assertEquals("Wool, at field/US", block.avoidedProducts.get(0).name);
		assertEquals("Soy oil, refined, at plant/kg/RNA", block.materialsAndFuels.get(0).name);
		assertEquals("Electricity, biomass, at power plant/US", block.electricityAndHeat.get(0).name);
		assertEquals("Dummy, Disposal, msw, to sanitary landfill/kg/GLO", block.wasteToTreatment.get(0).name);
	}

	@Test
	public void testParameters() {
		assertEquals(1, block.calculatedParameters.size());
		assertEquals(1, block.inputParameters.size());
		assertEquals("calc_param", block.calculatedParameters.get(0).name);
		assertEquals("input_param", block.inputParameters.get(0).name);
	}

	@Test
	public void testOtherEntries() {
		SimpleDateFormat format = new SimpleDateFormat(CsvConfig.getDefault()
				.getDateFormat());
		String dateString = format.format(block.date);
		assertEquals("24.02.2014", dateString);
		assertEquals(false, block.infrastructure);
	}

	@Test
	public void testLiteratureReferences() {
		assertEquals(1, block.literatureReferences.size());
		assertEquals("Ecoinvent 3", block.literatureReferences.get(0).name);
	}

	@Test
	public void testSystemDescription() {
		assertEquals("U.S. LCI Database", block.systemDescription.name);
	}
}
